---
- package:
    name: apt-transport-https
    state: present

- name: Install Package Cloud GPG key
  apt_key: url=https://packagecloud.io/gpg.key state=present

- name: Add APT repository
  apt_repository:
    repo: 'deb https://packagecloud.io/grafana/{{ grafana_repo_release }}/debian/ jessie main'
    state: present

- name: Install
  apt:
    name: "grafana={{ grafana_version }}"
    state: present
  register: install_packages
  until: install_packages is success
  retries: 5
  delay: 2
...
