---
- include: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"

- name: Install
  package:
    name: grafana
    state: installed

- name: Ensure directories
  file:
    path: {{ item }}
    owner: root
    group: root
    mode: 0644
    state: directory
  with_items:
      "{{ grafana_paths | values }}"

- name: Configure
  template:
    src: "grafana.ini.j2"
    dest: "{{ grafana_paths['conf'] | dirname }}/grafana.ini"
    owner: root
    group: root
    mode:  0644
  notify: restart grafana

- name: Provision - datasource
  template:
    src: "influxdb.yaml.j2"
    dest: "{{ grafana_paths['provisioning'] | dirname }}/datasources/influxdb.yaml"
    owner: root
    group: root
    mode:  0644
  notify: restart grafana

- name: Provision - dashboard
  template:
    src: "openio.json.j2"
    dest: "{{ grafana_paths['provisioning'] | dirname }}/dashboards/openio.json"
    owner: root
    group: root
    mode:  0644
  notify: restart grafana

- name: Start service
  service:
    name: "{{ grafana_service_name }}"
    state: started
    enabled: true
