---
- include: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"

- name: Install
  package:
    name: grafana
    state: installed

- name: Generate secret key
  register: grafana_secret
  command: "openssl rand -base64 64"

- name: Ensure directories
  file:
    path: "{{ item }}"
    owner: grafana
    group: grafana
    mode: 0644
    state: directory
  with_items:
      "{{ grafana_paths.values() }}"

- name: Configure
  template:
    src: "grafana.ini.j2"
    dest: "{{ grafana_paths['conf'] | realpath }}/grafana.ini"
    owner: grafana
    group: grafana
    mode:  0644
  notify: restart grafana

- name: Provision - datasource
  template:
    src: "influxdb.yaml.j2"
    dest: "{{ grafana_paths['datasources'] | realpath }}/influxdb.yaml"
    owner: grafana
    group: grafana
    mode:  0644
  notify: restart grafana

- name: Provision - dashboard JSON
  template:
    src: "openio.json.j2"
    dest: "{{ grafana_paths['dashboards'] | realpath }}/openio.json"
    owner: grafana
    group: grafana
    mode:  0644
  notify: restart grafana

- name: Provision - dashboard config
  template:
    src: "openio.yml.j2"
    dest: "{{ grafana_paths['dashboards'] | realpath }}/openio.yml"
    owner: grafana
    group: grafana
    mode:  0644
  notify: restart grafana

- name: Start service
  service:
    name: "{{ grafana_service_name }}"
    state: started
    enabled: true
