{
 "title": "OpenIO",
 "time": { "to": "now", "from": "now-30m" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "host", "query": "label_values(instance)" }
  ]
 },
 "panels": [
  {
   "title": "Overview",
   "type": "row",
   "gridPos": { "y": 0, "h": 1, "w": 24, "x": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Usage",
     "type": "singlestat",
     "gridPos": { "y": 1, "h": 6, "w": 6, "x": 0 },
     "format": "percent",
     "valueName": "current",
     "targets": [
      {
       "expr": "avg(netdata_system_cpu_percentage_average{chart=\"system.cpu\",family=\"cpu\",dimension=\"user\",instance=~\"[[host]]\"})",
       "tags": [
        { "operator": "=", "value": "idle", "key": "mode" },
        { "operator": "=", "value": "system", "key": "cpu", "condition": "AND" }
       ],
       "select": [
        [
         { "type": "field", "params": [ "value" ] },
         {
          "type": "last",
          "params": []
         }
        ]
       ],
       "measurement": "cpu",
       "query": "SELECT last(\"value\") * -1 + 100 FROM \"[[DS]]\".\"cpu\" WHERE \"host\" =~ /^$host$/ AND \"mode\" = 'idle' AND \"cpu\" = 'system' AND $timeFilter GROUP BY time([[ds_int]]) fill(null)",
       "groupBy": [
        { "type": "time", "params": [ "$__interval" ] },
        { "type": "fill", "params": [ "null" ] }
       ]
      }
     ]
    },
    {
     "title": "RAM Used",
     "type": "singlestat",
     "gridPos": { "y": 1, "h": 6, "w": 6, "x": 6 },
     "format": "decmbytes",
     "valueName": "avg",
     "targets": [
      {
       "expr": "sum(netdata_system_ram_MB_average{chart=\"system.ram\",family=\"ram\",dimension=\"used\",instance=~\"[[host]]\"})",
       "tags": [
        { "operator": "=~", "value": "/^$host$/", "key": "host" },
        { "operator": "=", "value": "used", "key": "type", "condition": "AND" }
       ],
       "select": [
        [
         { "type": "field", "params": [ "value" ] },
         {
          "type": "sum",
          "params": []
         }
        ]
       ],
       "measurement": "ram",
       "query": "SELECT sum(\"value\") FROM \"[[DS]]\".\"ram\" WHERE \"host\" =~ /^$host$/ AND \"type\" = 'used' AND $timeFilter GROUP BY time([[ds_int]]) fill(null)",
       "groupBy": [
        { "type": "time", "params": [ "$__interval" ] },
        { "type": "fill", "params": [ "null" ] }
       ]
      }
     ]
    },
    {
     "title": "DiskSpace Used",
     "type": "singlestat",
     "gridPos": { "y": 1, "h": 6, "w": 6, "x": 12 },
     "format": "decgbytes",
     "valueName": "avg",
     "targets": [
      {
       "expr": "sum(netdata_disk_space_GB_average{dimension=\"used\",instance=~\"[[host]]\"})",
       "tags": [
        { "operator": "=~", "value": "/^$host$/", "key": "host" },
        { "operator": "=", "value": "used", "key": "type", "condition": "AND" }
       ],
       "select": [
        [
         { "type": "field", "params": [ "value" ] },
         {
          "type": "sum",
          "params": []
         }
        ]
       ],
       "measurement": "disk_space",
       "query": "SELECT sum(\"value\") FROM \"[[DS]]\".\"disk_space\" WHERE \"host\" =~ /^$host$/ AND \"type\" = 'used' AND $timeFilter GROUP BY time([[ds_int]]) fill(null)",
       "groupBy": [
        { "type": "time", "params": [ "$__interval" ] },
        { "type": "fill", "params": [ "null" ] }
       ]
      }
     ]
    },
    {
     "title": "Network Bandwidth",
     "type": "singlestat",
     "gridPos": { "y": 1, "h": 6, "w": 6, "x": 18 },
     "format": "Kbits",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(netdata_net_net_kilobits_persec_average{dimension=\"received\", instance=~\"[[host]]\"}) + sum(netdata_net_net_kilobits_persec_average{dimension=\"received\", instance=~\"[[host]]\"})\n",
       "tags": [
        { "operator": "=~", "value": "/^$host$/", "key": "host" },
        { "operator": "=", "value": "received", "key": "type", "condition": "AND" }
       ],
       "select": [
        [
         { "type": "field", "params": [ "value" ] },
         {
          "type": "sum",
          "params": []
         }
        ]
       ],
       "measurement": "net",
       "query": "SELECT sum(\"value\") FROM \"[[DS]]\".\"net\" WHERE \"host\" =~ /^$host$/ AND \"type\" = 'received' AND $timeFilter GROUP BY time([[ds_int]]) fill(null)",
       "groupBy": [
        { "type": "time", "params": [ "$__interval" ] },
        { "type": "fill", "params": [ "null" ] }
       ]
      }
     ]
    }
   ]
  },
  { "title": "System", "type": "row", "gridPos": { "y": 1, "h": 1, "w": 24, "x": 0 } },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "y": 2, "h": 7, "w": 12, "x": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(netdata_system_cpu_percentage_average{chart=\"system.cpu\",family=\"cpu\",instance=~\"[[host]]\"}) by (dimension)",
     "alias": "$tag_mode",
     "tags": [
      { "operator": "=", "value": "system", "key": "cpu" }
     ],
     "select": [
      [
       { "type": "field", "params": [ "value" ] },
       {
        "type": "mean",
        "params": []
       }
      ]
     ],
     "legendFormat": "{{dimension}}",
     "measurement": "cpu",
     "query": "SELECT mean(\"value\") FROM \"[[DS]]\".\"cpu\" WHERE (\"cpu\" = 'system') AND $timeFilter GROUP BY time([[ds_int]]), \"mode\" fill(null)",
     "groupBy": [
      { "type": "time", "params": [ "$__interval" ] },
      { "type": "tag", "params": [ "mode" ] },
      { "type": "fill", "params": [ "null" ] }
     ]
    }
   ]
  },
  {
   "title": "RAM Usage",
   "type": "graph",
   "gridPos": { "y": 2, "h": 7, "w": 12, "x": 12 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "expr": "sum(netdata_system_ram_MB_average{chart=\"system.ram\",family=\"ram\",instance=~\"[[host]]\"}) by (dimension)",
     "alias": "$tag_type",
     "tags": [
      { "operator": "=~", "value": "/^$host$/", "key": "host" }
     ],
     "select": [
      [
       { "type": "field", "params": [ "value" ] },
       {
        "type": "sum",
        "params": []
       }
      ]
     ],
     "legendFormat": "{{dimension}}",
     "measurement": "ram",
     "groupBy": [
      { "type": "time", "params": [ "$__interval" ] },
      { "type": "tag", "params": [ "type" ] },
      { "type": "fill", "params": [ "null" ] }
     ]
    }
   ]
  },
  {
   "title": "Load Average",
   "type": "graph",
   "gridPos": { "y": 9, "h": 7, "w": 12, "x": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(netdata_system_load_load_average{chart=\"system.load\",family=\"load\",instance=~\"[[host]]\"}) by (dimension)\n",
     "alias": "$tag_avg",
     "tags": [
      { "operator": "=~", "value": "/^$host$/", "key": "host" }
     ],
     "select": [
      [
       { "type": "field", "params": [ "value" ] },
       {
        "type": "sum",
        "params": []
       }
      ]
     ],
     "legendFormat": "{{dimension }}",
     "measurement": "load",
     "query": "SELECT sum(\"value\") FROM \"[[DS]]\".\"load\" WHERE \"host\" =~ /^$host$/ AND $timeFilter GROUP BY time([[ds_int]]), \"avg\" fill(null)",
     "groupBy": [
      { "type": "time", "params": [ "$__interval" ] },
      { "type": "tag", "params": [ "avg" ] },
      { "type": "fill", "params": [ "null" ] }
     ]
    }
   ]
  },
  {
   "title": "Context Switches",
   "type": "graph",
   "gridPos": { "y": 9, "h": 7, "w": 12, "x": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(netdata_system_ctxt_context_switches_persec_average{chart=\"system.ctxt\",family=\"processes\",dimension=\"switches\",instance=~\"[[host]]\"})\n",
     "alias": "context_switches",
     "tags": [
      { "operator": "=~", "value": "/^$host$/", "key": "host" }
     ],
     "select": [
      [
       { "type": "field", "params": [ "value" ] },
       {
        "type": "sum",
        "params": []
       }
      ]
     ],
     "legendFormat": "context switches",
     "measurement": "ctxt_switches",
     "query": "SELECT sum(\"value\")  FROM \"[[DS]]\".\"ctxt_switches\" WHERE \"host\" =~ /^$host$/ AND $timeFilter GROUP BY time([[ds_int]]) fill(null)",
     "groupBy": [
      { "type": "time", "params": [ "$__interval" ] },
      { "type": "fill", "params": [ "null" ] }
     ]
    }
   ]
  },
  {
   "title": "Processes",
   "type": "graph",
   "gridPos": { "y": 16, "h": 7, "w": 12, "x": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(netdata_system_processes_processes_average{chart=\"system.processes\",family=\"processes\",dimension=\"running\",instance=~\"[[host]]\"})",
     "alias": "$tag_type",
     "select": [
      [
       { "type": "field", "params": [ "value" ] },
       {
        "type": "sum",
        "params": []
       }
      ]
     ],
     "legendFormat": "running",
     "measurement": "processes",
     "query": "SELECT sum(\"value\") FROM \"[[DS]]\".\"processes\" WHERE $timeFilter GROUP BY time([[ds_int]]), \"type\" fill(null)",
     "groupBy": [
      { "type": "time", "params": [ "$__interval" ] },
      { "type": "tag", "params": [ "type" ] },
      { "type": "fill", "params": [ "null" ] }
     ]
    }
   ]
  },
  {
   "title": "Commited Memory",
   "type": "graph",
   "gridPos": { "y": 16, "h": 7, "w": 12, "x": 12 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "expr": "sum(netdata_mem_committed_MB_average{chart=\"mem.committed\",family=\"system\",dimension=\"Committed_AS\",instance=~\"[[host]]\"})",
     "alias": "commited_memory",
     "tags": [
      { "operator": "=~", "value": "/^$host$/", "key": "host" }
     ],
     "select": [
      [
       { "type": "field", "params": [ "value" ] },
       {
        "type": "sum",
        "params": []
       }
      ]
     ],
     "legendFormat": "committed memory",
     "measurement": "mem_committed",
     "query": "SELECT sum(\"value\") FROM \"[[DS]]\".\"mem_committed\" WHERE \"host\" =~ /^$host$/ AND $timeFilter GROUP BY time([[ds_int]]) fill(null)",
     "groupBy": [
      { "type": "time", "params": [ "$__interval" ] },
      { "type": "fill", "params": [ "null" ] }
     ]
    }
   ]
  },
  {
   "title": "Open files",
   "type": "graph",
   "gridPos": { "y": 23, "h": 8, "w": 24, "x": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(netdata_apps_files_open_files_average{instance=~\"[[host]]\"}) by (dimension)",
     "legendFormat": "{{dimension}}"
    }
   ]
  },
  {
   "title": "Disk",
   "type": "row",
   "gridPos": { "y": 31, "h": 1, "w": 24, "x": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Disk Throughput",
     "type": "graph",
     "gridPos": { "y": 12, "h": 7, "w": 12, "x": 0 },
     "yaxes": [
      { "format": "KBs" }
     ],
     "targets": [
      {
       "expr": "sum(netdata_disk_io_kilobytes_persec_average{instance=~\"[[host]]\", dimension=\"reads\"})",
       "alias": "$tag_operation",
       "tags": [
        { "operator": "=~", "value": "/^$host$/", "key": "host" }
       ],
       "select": [
        [
         { "type": "field", "params": [ "value" ] },
         {
          "type": "sum",
          "params": []
         }
        ]
       ],
       "legendFormat": "read",
       "measurement": "io",
       "query": "SELECT sum(\"value\") FROM \"[[DS]]\".\"io\" WHERE \"host\" =~ /^$host$/ AND $timeFilter GROUP BY time([[ds_int]]), \"operation\" fill(null)",
       "groupBy": [
        { "type": "time", "params": [ "$__interval" ] },
        { "type": "tag", "params": [ "operation" ] },
        { "type": "fill", "params": [ "null" ] }
       ]
      },
      {
       "expr": "-sum(netdata_disk_io_kilobytes_persec_average{instance=~\"[[host]]\", dimension=\"writes\"})",
       "legendFormat": "write"
      }
     ]
    },
    {
     "title": "Disk IOps",
     "type": "graph",
     "gridPos": { "y": 12, "h": 7, "w": 12, "x": 12 },
     "yaxes": [
      { "format": "iops" }
     ],
     "targets": [
      {
       "expr": "sum(netdata_disk_ops_operations_persec_average{instance=~\"[[host]]\"}) by (dimension)",
       "alias": "$tag_operation",
       "tags": [
        { "operator": "=~", "value": "/^$host$/", "key": "host" }
       ],
       "select": [
        [
         { "type": "field", "params": [ "value" ] },
         {
          "type": "sum",
          "params": []
         }
        ]
       ],
       "legendFormat": "{{dimension}}",
       "measurement": "disk_ops",
       "groupBy": [
        { "type": "time", "params": [ "$__interval" ] },
        { "type": "tag", "params": [ "operation" ] },
        { "type": "fill", "params": [ "null" ] }
       ]
      }
     ]
    },
    {
     "title": "Disk Usage",
     "type": "graph",
     "gridPos": { "y": 19, "h": 7, "w": 12, "x": 0 },
     "yaxes": [
      { "format": "decgbytes" }
     ],
     "targets": [
      {
       "expr": "sum(netdata_disk_space_GB_average{instance=~\"[[host]]\"}) by (dimension)",
       "alias": "$tag_type",
       "tags": [
        { "operator": "=~", "value": "/^$host$/", "key": "host" }
       ],
       "select": [
        [
         { "type": "field", "params": [ "value" ] },
         {
          "type": "sum",
          "params": []
         }
        ]
       ],
       "legendFormat": "{{dimension}}",
       "measurement": "disk_space",
       "query": "SELECT sum(\"value\") FROM \"[[DS]]\".\"disk_space\" WHERE \"host\" =~ /^$host$/ AND $timeFilter GROUP BY time([[ds_int]]), \"type\"",
       "groupBy": [
        { "type": "time", "params": [ "$__interval" ] },
        { "type": "tag", "params": [ "type" ] }
       ]
      }
     ]
    },
    {
     "title": "Disk Files Usage",
     "type": "graph",
     "gridPos": { "y": 19, "h": 7, "w": 12, "x": 12 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(netdata_disk_inodes_Inodes_average{instance=~\"[[host]]\"}) by (dimension)\n",
       "alias": "$tag_type",
       "tags": [
        { "operator": "=~", "value": "/^$host$/", "key": "host" }
       ],
       "select": [
        [
         { "type": "field", "params": [ "value" ] },
         {
          "type": "sum",
          "params": []
         }
        ]
       ],
       "legendFormat": "{{dimension}}",
       "measurement": "disk_inodes",
       "query": "SELECT sum(\"value\") FROM \"[[DS]]\".\"disk_inodes\" WHERE \"host\" =~ /^$host$/ AND $timeFilter GROUP BY time([[ds_int]]), \"type\" fill(null)",
       "groupBy": [
        { "type": "time", "params": [ "$__interval" ] },
        { "type": "tag", "params": [ "type" ] },
        { "type": "fill", "params": [ "null" ] }
       ]
      }
     ]
    },
    {
     "title": "Disk Backlog",
     "type": "graph",
     "gridPos": { "y": 26, "h": 7, "w": 12, "x": 0 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "quantile(0.95, avg(netdata_disk_backlog_backlog__ms__average{dimension=\"backlog\",instance=~\"[[host]]\"}))",
       "alias": "maximum",
       "tags": [
        { "operator": "=~", "value": "/^$host$/", "key": "host" }
       ],
       "select": [
        [
         { "type": "field", "params": [ "value" ] },
         {
          "type": "max",
          "params": []
         }
        ]
       ],
       "legendFormat": "95th percentile",
       "measurement": "disk_backlog",
       "query": "SELECT max(\"value\") FROM \"[[DS]]\".\"disk_backlog\" WHERE \"host\" =~ /^$host$/ AND $timeFilter GROUP BY time([[ds_int]]) fill(null)",
       "groupBy": [
        { "type": "time", "params": [ "$__interval" ] },
        { "type": "fill", "params": [ "null" ] }
       ]
      },
      {
       "expr": "avg(netdata_disk_backlog_backlog__ms__average{dimension=\"backlog\",instance=~\"[[host]]\"})",
       "legendFormat": "maximum"
      }
     ]
    },
    {
     "title": "Disk Utilization",
     "type": "graph",
     "gridPos": { "y": 26, "h": 7, "w": 12, "x": 12 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "avg(netdata_disk_util___of_time_working_average{dimension=\"utilization\",instance=~\"[[host]]\"})",
       "alias": "maximum",
       "tags": [
        { "operator": "=~", "value": "/^$host$/", "key": "host" }
       ],
       "select": [
        [
         { "type": "field", "params": [ "value" ] },
         {
          "type": "max",
          "params": []
         }
        ]
       ],
       "legendFormat": "maximum",
       "measurement": "disk_util",
       "query": "SELECT max(\"value\") FROM \"[[DS]]\".\"disk_util\" WHERE (\"host\" =~ /^$host$/) AND $timeFilter GROUP BY time([[ds_int]]) fill(null)",
       "groupBy": [
        { "type": "time", "params": [ "$__interval" ] },
        { "type": "fill", "params": [ "null" ] }
       ]
      },
      {
       "expr": "quantile(0.95, avg(netdata_disk_util___of_time_working_average{dimension=\"utilization\",instance=~\"[[host]]\"}))",
       "legendFormat": "95th percentile"
      }
     ]
    }
   ]
  },
  {
   "title": "Network Interfaces",
   "type": "row",
   "gridPos": { "y": 32, "h": 1, "w": 24, "x": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Network Usage",
     "type": "graph",
     "gridPos": { "y": 13, "h": 7, "w": 12, "x": 0 },
     "yaxes": [
      { "format": "Kbits" }
     ],
     "targets": [
      {
       "expr": "sum(netdata_net_net_kilobits_persec_average{instance=~\"[[host]]\"}) by (dimension)",
       "alias": "$tag_type",
       "tags": [
        { "operator": "=~", "value": "/^$host$/", "key": "host" }
       ],
       "select": [
        [
         { "type": "field", "params": [ "value" ] },
         {
          "type": "sum",
          "params": []
         }
        ]
       ],
       "legendFormat": "{{dimension}}",
       "measurement": "net",
       "query": "SELECT sum(\"value\") FROM \"[[DS]]\".\"net\" WHERE \"host\" =~ /^$host$/ AND $timeFilter GROUP BY time([[ds_int]]), \"type\" fill(null)",
       "groupBy": [
        { "type": "time", "params": [ "$__interval" ] },
        { "type": "tag", "params": [ "type" ] },
        { "type": "fill", "params": [ "null" ] }
       ]
      }
     ]
    },
    {
     "title": "Network Packets",
     "type": "graph",
     "gridPos": { "y": 13, "h": 7, "w": 12, "x": 12 },
     "yaxes": [
      { "format": "pps" }
     ],
     "targets": [
      {
       "expr": "sum(netdata_net_packets_packets_persec_average{instance=~\"[[host]]\"}) by (dimension)",
       "alias": "$tag_type",
       "tags": [
        { "operator": "=~", "value": "/^$host$/", "key": "host" }
       ],
       "select": [
        [
         { "type": "field", "params": [ "value" ] },
         {
          "type": "sum",
          "params": []
         }
        ]
       ],
       "legendFormat": "{{dimension}}",
       "measurement": "net_packets",
       "groupBy": [
        { "type": "time", "params": [ "$__interval" ] },
        { "type": "tag", "params": [ "type" ] },
        { "type": "fill", "params": [ "null" ] }
       ]
      }
     ]
    },
    {
     "title": "Network Drops",
     "type": "graph",
     "gridPos": { "y": 20, "h": 7, "w": 12, "x": 0 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(netdata_net_drops_drops_persec_average{instance=~\"[[host]]\"}) by (dimension)",
       "alias": "$tag_type",
       "tags": [
        { "operator": "=~", "value": "/^$host$/", "key": "host" }
       ],
       "select": [
        [
         { "type": "field", "params": [ "value" ] },
         {
          "type": "sum",
          "params": []
         }
        ]
       ],
       "legendFormat": "{{dimension}}",
       "measurement": "net_drops",
       "query": "SELECT sum(\"value\") FROM \"[[DS]]\".\"net_drops\" WHERE \"host\" =~ /^$host$/ AND $timeFilter GROUP BY time([[ds_int]]), \"type\" fill(null)",
       "groupBy": [
        { "type": "time", "params": [ "$__interval" ] },
        { "type": "tag", "params": [ "type" ] },
        { "type": "fill", "params": [ "null" ] }
       ]
      }
     ]
    },
    {
     "title": "Network Errors",
     "type": "graph",
     "gridPos": { "y": 20, "h": 7, "w": 12, "x": 12 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(netdata_ipv4_errors_packets_persec_average{instance=~\"[[host]]\"}) by (dimension)",
       "alias": "$tag_type",
       "tags": [
        { "operator": "=~", "value": "/^$host$/", "key": "host" }
       ],
       "select": [
        [
         { "type": "field", "params": [ "value" ] },
         {
          "type": "sum",
          "params": []
         }
        ]
       ],
       "legendFormat": "{{dimension}}",
       "measurement": "ipv4_errors",
       "query": "SELECT sum(\"value\") FROM \"[[DS]]\".\"ipv4_errors\" WHERE \"host\" =~ /^$host$/ AND $timeFilter GROUP BY time([[ds_int]]), \"type\" fill(null)",
       "groupBy": [
        { "type": "time", "params": [ "$__interval" ] },
        { "type": "tag", "params": [ "type" ] },
        { "type": "fill", "params": [ "null" ] }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "IPv4 Networking",
   "type": "row",
   "gridPos": { "y": 33, "h": 1, "w": 24, "x": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Packets",
     "type": "graph",
     "gridPos": { "y": 5, "h": 7, "w": 12, "x": 0 },
     "yaxes": [
      { "format": "pps" }
     ],
     "targets": [
      {
       "expr": "sum(netdata_ipv4_packets_packets_persec_average{chart=\"ipv4.packets\",family=\"packets\",instance=~\"[[host]]\"}) by (dimension)",
       "alias": "$tag_type",
       "tags": [
        { "operator": "=~", "value": "/^$host$/", "key": "host" }
       ],
       "select": [
        [
         { "type": "field", "params": [ "value" ] },
         {
          "type": "sum",
          "params": []
         }
        ]
       ],
       "legendFormat": "{{dimension}}",
       "measurement": "ipv4_packets",
       "query": "SELECT sum(\"value\") FROM \"[[DS]]\".\"ipv4_packets\" WHERE \"host\" =~ /^$host$/ AND $timeFilter GROUP BY time([[ds_int]]), \"type\" fill(null)\n\n",
       "groupBy": [
        { "type": "time", "params": [ "$__interval" ] },
        { "type": "tag", "params": [ "type" ] },
        { "type": "fill", "params": [ "null" ] }
       ]
      }
     ]
    },
    {
     "title": "Errors",
     "type": "graph",
     "gridPos": { "y": 5, "h": 7, "w": 12, "x": 12 },
     "yaxes": [
      { "format": "pps" }
     ],
     "targets": [
      {
       "expr": "sum(netdata_ipv4_errors_packets_persec_average{chart=\"ipv4.errors\",family=\"errors\",instance=~\"[[host]]\"}) by (dimension)",
       "alias": "$tag_type",
       "select": [
        [
         { "type": "field", "params": [ "value" ] },
         {
          "type": "mean",
          "params": []
         }
        ]
       ],
       "legendFormat": "{{dimension}}",
       "measurement": "ipv4_errors",
       "query": "SELECT sum(\"value\") FROM \"[[DS]]\".\"ipv4_errors\" WHERE $timeFilter GROUP BY time([[ds_int]]), \"type\" fill(null)",
       "groupBy": [
        { "type": "time", "params": [ "$__interval" ] },
        { "type": "tag", "params": [ "type" ] },
        { "type": "fill", "params": [ "null" ] }
       ]
      }
     ]
    },
    {
     "title": "TCP connections",
     "type": "graph",
     "gridPos": { "y": 12, "h": 7, "w": 12, "x": 0 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(netdata_ipv4_tcpsock_active_connections_average{chart=\"ipv4.tcpsock\",family=\"tcp\",dimension=\"connections\",instance=~\"[[host]]\"})",
       "alias": "established",
       "tags": [
        { "operator": "=~", "value": "/^$host$/", "key": "host" }
       ],
       "select": [
        [
         { "type": "field", "params": [ "value" ] },
         {
          "type": "sum",
          "params": []
         }
        ]
       ],
       "legendFormat": "established",
       "measurement": "ipv4_tcpsock",
       "query": "SELECT sum(\"value\") FROM \"[[DS]]\".\"ipv4_tcpsock\" WHERE \"host\" =~ /^$host$/ AND $timeFilter GROUP BY time([[ds_int]]), \"type\" fill(null)",
       "groupBy": [
        { "type": "time", "params": [ "$__interval" ] },
        { "type": "tag", "params": [ "type" ] },
        { "type": "fill", "params": [ "null" ] }
       ]
      }
     ]
    },
    {
     "title": "TCP Handshakes",
     "type": "graph",
     "gridPos": { "y": 12, "h": 7, "w": 12, "x": 12 },
     "yaxes": [
      { "format": "pps" }
     ],
     "targets": [
      {
       "expr": "sum(netdata_ipv4_tcphandshake_events_persec_average{chart=\"ipv4.tcphandshake\",family=\"tcp\",instance=~\"[[host]]\"}) by (dimension)",
       "alias": "$tag_type",
       "select": [
        [
         { "type": "field", "params": [ "value" ] },
         {
          "type": "sum",
          "params": []
         }
        ]
       ],
       "legendFormat": "{{dimension}}",
       "measurement": "ipv4_tcphandshake",
       "query": "SELECT sum(\"value\") FROM \"[[DS]]\".\"ipv4_tcphandshake\" WHERE $timeFilter GROUP BY time([[ds_int]]), \"type\" fill(null)",
       "groupBy": [
        { "type": "time", "params": [ "$__interval" ] },
        { "type": "tag", "params": [ "type" ] },
        { "type": "fill", "params": [ "null" ] }
       ]
      }
     ]
    },
    {
     "title": "TCP Errors",
     "type": "graph",
     "gridPos": { "y": 19, "h": 7, "w": 12, "x": 0 },
     "yaxes": [
      { "format": "pps" }
     ],
     "targets": [
      {
       "expr": "sum(netdata_ipv4_tcperrors_packets_persec_average{chart=\"ipv4.tcperrors\",family=\"tcp\",instance=~\"[[host]]\"}) by (dimension)",
       "alias": "$tag_type",
       "select": [
        [
         { "type": "field", "params": [ "value" ] },
         {
          "type": "sum",
          "params": []
         }
        ]
       ],
       "legendFormat": "{{dimension}}",
       "measurement": "ipv4_tcperrors",
       "query": "SELECT sum(\"value\") FROM \"[[DS]]\".\"ipv4_tcperrors\" WHERE $timeFilter GROUP BY time([[ds_int]]), \"type\" fill(null)",
       "groupBy": [
        { "type": "time", "params": [ "$__interval" ] },
        { "type": "tag", "params": [ "type" ] },
        { "type": "fill", "params": [ "null" ] }
       ]
      }
     ]
    },
    {
     "title": "UDP Packets",
     "type": "graph",
     "gridPos": { "y": 19, "h": 7, "w": 12, "x": 12 },
     "yaxes": [
      { "format": "pps" }
     ],
     "targets": [
      {
       "expr": "sum(netdata_ipv4_udppackets_packets_persec_average{chart=\"ipv4.udppackets\",family=\"udp\",instance=~\"[[host]]\"}) by (dimension)",
       "alias": "$tag_type",
       "tags": [
        { "operator": "=~", "value": "/^$host$/", "key": "host" }
       ],
       "select": [
        [
         { "type": "field", "params": [ "value" ] },
         {
          "type": "sum",
          "params": []
         }
        ]
       ],
       "legendFormat": "{{dimension}}",
       "measurement": "ipv4_udppackets",
       "query": "SELECT sum(\"value\") FROM \"[[DS]]\".\"ipv4_udppackets\" WHERE \"host\" =~ /^$host$/ AND $timeFilter GROUP BY time([[ds_int]]), \"type\" fill(null)",
       "groupBy": [
        { "type": "time", "params": [ "$__interval" ] },
        { "type": "tag", "params": [ "type" ] },
        { "type": "fill", "params": [ "null" ] }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "OpenIO System",
   "type": "row",
   "gridPos": { "y": 34, "h": 1, "w": 24, "x": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Usage",
     "type": "graph",
     "gridPos": { "y": 6, "h": 7, "w": 12, "x": 0 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "sum(netdata_apps_cpu_system_cpu_time___average{chart=\"apps.cpu_system\",family=\"cpu\",instance=~\"[[host]]\"}) by (dimension)",
       "alias": "$tag_servicetype: $tag_mode",
       "tags": [
        { "operator": "=", "value": "cpu", "key": "resource" },
        { "operator": "=", "value": "used", "key": "mode", "condition": "AND" }
       ],
       "select": [
        [
         { "type": "field", "params": [ "value" ] },
         {
          "type": "sum",
          "params": []
         }
        ]
       ],
       "legendFormat": "{{dimension}}",
       "measurement": "openio",
       "query": "SELECT sum(\"value\") FROM \"[[DS]]\".\"apps_cpu\" WHERE \"app\" = 'openio' AND $timeFilter GROUP BY time([[ds_int]]), \"servicetype\" fill(null)",
       "groupBy": [
        { "type": "time", "params": [ "$__interval" ] },
        { "type": "tag", "params": [ "mode" ] },
        { "type": "tag", "params": [ "servicetype" ] },
        { "type": "fill", "params": [ "null" ] }
       ]
      }
     ]
    },
    {
     "title": "Disk Throughput",
     "type": "graph",
     "gridPos": { "y": 6, "h": 7, "w": 12, "x": 12 },
     "yaxes": [
      { "format": "KBs" }
     ],
     "targets": [
      {
       "expr": "sum(netdata_apps_preads_kilobytes_persec_average{chart=\"apps.preads\",family=\"disk\",instance=~\"[[host]]\"}) by (dimension)",
       "alias": "$tag_servicetype: $tag_type",
       "tags": [
        { "operator": "=", "value": "disk", "key": "resource" },
        { "operator": "=", "value": "read", "key": "type", "condition": "AND" }
       ],
       "select": [
        [
         { "type": "field", "params": [ "value" ] },
         {
          "type": "sum",
          "params": []
         }
        ]
       ],
       "legendFormat": "reads - {{dimension}}",
       "measurement": "openio",
       "query": "SELECT sum(\"value\") FROM \"[[DS]]\".\"apps_preads\" WHERE \"app\" = 'openio' AND $timeFilter GROUP BY time([[ds_int]]), \"servicetype\" fill(null)",
       "groupBy": [
        { "type": "time", "params": [ "$__interval" ] },
        { "type": "tag", "params": [ "servicetype" ] },
        { "type": "tag", "params": [ "type" ] },
        { "type": "fill", "params": [ "null" ] }
       ]
      },
      {
       "expr": "sum(netdata_apps_pwrites_kilobytes_persec_average{chart=\"apps.pwrites\",family=\"disk\",instance=~\"[[host]]\"}) by (dimension)",
       "alias": "$tag_servicetype: $tag_type",
       "tags": [
        { "operator": "=", "value": "disk", "key": "resource" },
        { "operator": "=", "value": "write", "key": "type", "condition": "AND" }
       ],
       "select": [
        [
         { "type": "field", "params": [ "value" ] },
         {
          "type": "sum",
          "params": []
         }
        ]
       ],
       "legendFormat": "writes - {{dimension}}",
       "measurement": "openio",
       "query": "SELECT (sum(\"value\") * -1) FROM \"[[DS]]\".\"apps_pwrites\" WHERE \"app\" = 'openio' AND $timeFilter GROUP BY time([[ds_int]]), \"servicetype\" fill(null)",
       "groupBy": [
        { "type": "time", "params": [ "$__interval" ] },
        { "type": "tag", "params": [ "servicetype" ] },
        { "type": "tag", "params": [ "type" ] },
        { "type": "fill", "params": [ "null" ] }
       ]
      }
     ]
    },
    {
     "title": "Open Files",
     "type": "graph",
     "gridPos": { "y": 13, "h": 7, "w": 12, "x": 0 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(netdata_apps_files_open_files_average{chart=\"apps.files\",family=\"disk\",instance=~\"[[host]]\"}) by (dimension)\n",
       "alias": "$tag_servicetype",
       "tags": [
        { "operator": "=", "value": "files", "key": "resource" }
       ],
       "select": [
        [
         { "type": "field", "params": [ "value" ] },
         {
          "type": "sum",
          "params": []
         }
        ]
       ],
       "legendFormat": "{{dimension}}",
       "measurement": "openio",
       "query": "SELECT sum(\"value\") FROM \"[[DS]]\".\"apps_files\" WHERE \"app\" = 'openio' AND $timeFilter GROUP BY time([[ds_int]]), \"servicetype\" fill(null)",
       "groupBy": [
        { "type": "time", "params": [ "$__interval" ] },
        { "type": "tag", "params": [ "servicetype" ] },
        { "type": "fill", "params": [ "null" ] }
       ]
      }
     ]
    },
    {
     "title": "Memory Usage",
     "type": "graph",
     "gridPos": { "y": 13, "h": 7, "w": 12, "x": 12 },
     "yaxes": [
      { "format": "decmbytes" }
     ],
     "targets": [
      {
       "expr": "sum(netdata_apps_mem_MB_average{chart=\"apps.mem\",family=\"mem\",instance=~\"[[host]]\"}) by (dimension)\n",
       "alias": "$tag_servicetype",
       "tags": [
        { "operator": "=", "value": "mem", "key": "resource" }
       ],
       "select": [
        [
         { "type": "field", "params": [ "value" ] },
         {
          "type": "sum",
          "params": []
         }
        ]
       ],
       "legendFormat": "{{dimension}}",
       "measurement": "openio",
       "query": "SELECT sum(\"value\") FROM \"[[DS]]\".\"apps_mem\" WHERE \"app\" = 'openio' AND $timeFilter GROUP BY time([[ds_int]]), \"servicetype\" fill(null)",
       "groupBy": [
        { "type": "time", "params": [ "$__interval" ] },
        { "type": "tag", "params": [ "servicetype" ] },
        { "type": "fill", "params": [ "null" ] }
       ]
      }
     ]
    },
    {
     "title": "Processes",
     "type": "graph",
     "gridPos": { "y": 20, "h": 7, "w": 12, "x": 0 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(netdata_apps_processes_processes_average{chart=\"apps.processes\",family=\"processes\",instance=~\"[[host]]\"}) by (dimension)",
       "alias": "$tag_servicetype",
       "tags": [
        { "operator": "=", "value": "processes", "key": "resource" }
       ],
       "select": [
        [
         { "type": "field", "params": [ "value" ] },
         {
          "type": "sum",
          "params": []
         }
        ]
       ],
       "legendFormat": "{{dimension}}",
       "measurement": "openio",
       "query": "SELECT sum(\"value\") FROM \"[[DS]]\".\"apps_processes\" WHERE \"app\" = 'openio' AND $timeFilter GROUP BY time([[ds_int]]), \"servicetype\" fill(null)",
       "groupBy": [
        { "type": "time", "params": [ "$__interval" ] },
        { "type": "tag", "params": [ "servicetype" ] },
        { "type": "fill", "params": [ "null" ] }
       ]
      }
     ]
    },
    {
     "title": "Threads",
     "type": "graph",
     "gridPos": { "y": 20, "h": 7, "w": 12, "x": 12 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(netdata_apps_threads_threads_average{chart=\"apps.threads\",family=\"processes\",instance=~\"[[host]]\"}) by (dimension)",
       "alias": "$tag_servicetype",
       "tags": [
        { "operator": "=", "value": "threads", "key": "resource" }
       ],
       "select": [
        [
         { "type": "field", "params": [ "value" ] },
         {
          "type": "sum",
          "params": []
         }
        ]
       ],
       "legendFormat": "{{dimension}}",
       "measurement": "openio",
       "query": "SELECT sum(\"value\") FROM \"[[DS]]\".\"apps_threads\" WHERE \"app\" = 'openio' AND $timeFilter GROUP BY time([[ds_int]]), \"servicetype\" fill(null)",
       "groupBy": [
        { "type": "time", "params": [ "$__interval" ] },
        { "type": "tag", "params": [ "servicetype" ] },
        { "type": "fill", "params": [ "null" ] }
       ]
      }
     ]
    },
    {
     "title": "Opened Sockets",
     "type": "graph",
     "gridPos": { "y": 27, "h": 7, "w": 12, "x": 0 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(netdata_apps_sockets_open_sockets_average{chart=\"apps.sockets\",family=\"net\",instance=~\"[[host]]\"}) by (dimension)",
       "alias": "$tag_servicetype",
       "tags": [
        { "operator": "=", "value": "sockets", "key": "resource" }
       ],
       "select": [
        [
         { "type": "field", "params": [ "value" ] },
         {
          "type": "sum",
          "params": []
         }
        ]
       ],
       "legendFormat": "{{dimension}}",
       "measurement": "openio",
       "query": "SELECT sum(\"value\") FROM \"[[DS]]\".\"apps_sockets\" WHERE \"app\" = 'openio' AND $timeFilter GROUP BY time([[ds_int]]), \"servicetype\" fill(null)",
       "groupBy": [
        { "type": "time", "params": [ "$__interval" ] },
        { "type": "tag", "params": [ "servicetype" ] },
        { "type": "fill", "params": [ "null" ] }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "OpenIO Services",
   "type": "row",
   "gridPos": { "y": 35, "h": 1, "w": 24, "x": 0 },
   "collapsed": true,
   "panels": [
    { "type": "text", "gridPos": { "y": 16, "h": 2, "w": 24, "x": 0 }, "content": "# Score" },
    {
     "title": "Score",
     "type": "singlestat",
     "gridPos": { "y": 18, "h": 8, "w": 6, "x": 0 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "expr": "avg(netdata_openio_score__average{instance=~\"[[host]]\"})",
       "select": [
        [
         { "type": "field", "params": [ "value" ] },
         {
          "type": "mean",
          "params": []
         }
        ]
       ],
       "groupBy": [
        { "type": "time", "params": [ "$__interval" ] },
        { "type": "fill", "params": [ "null" ] }
       ]
      }
     ]
    },
    {
     "title": "Score",
     "type": "graph",
     "gridPos": { "y": 18, "h": 8, "w": 11, "x": 6 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "aggr:netdata_openio_score:avg_per_service",
       "legendFormat": "{{dim2}}"
      }
     ]
    },
    {
     "title": "Score distribution",
     "type": "heatmap",
     "gridPos": { "y": 18, "h": 8, "w": 7, "x": 17 },
     "targets": [
      {
       "expr": "avg(netdata_openio_score__average{instance=~\"[[host]]\"}) by (dimension)",
       "select": [
        [
         { "type": "field", "params": [ "value" ] },
         {
          "type": "mean",
          "params": []
         }
        ]
       ],
       "legendFormat": "{{dimension}}",
       "groupBy": [
        { "type": "time", "params": [ "$__interval" ] },
        { "type": "fill", "params": [ "null" ] }
       ]
      }
     ]
    },
    { "type": "text", "gridPos": { "y": 26, "h": 2, "w": 24, "x": 0 }, "content": "# Storage" },
    {
     "title": "Data",
     "type": "singlestat",
     "gridPos": { "y": 28, "h": 5, "w": 6, "x": 0 },
     "format": "decbytes",
     "valueName": "avg",
     "targets": [
      {
       "expr": "sum(netdata_openio_container_bytes__average)",
       "select": [
        [
         { "type": "field", "params": [ "value" ] },
         {
          "type": "mean",
          "params": []
         }
        ]
       ],
       "groupBy": [
        { "type": "time", "params": [ "$__interval" ] },
        { "type": "fill", "params": [ "null" ] }
       ]
      }
     ]
    },
    {
     "title": "Top 10 largest containers (size)",
     "type": "graph",
     "gridPos": { "y": 28, "h": 8, "w": 9, "x": 6 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "topk(10, netdata_openio_container_bytes__average)",
       "select": [
        [
         { "type": "field", "params": [ "value" ] },
         {
          "type": "mean",
          "params": []
         }
        ]
       ],
       "legendFormat": "{{dimension}}",
       "groupBy": [
        { "type": "time", "params": [ "$__interval" ] },
        { "type": "fill", "params": [ "null" ] }
       ]
      }
     ]
    },
    {
     "title": "Top 10 accounts with most containers",
     "type": "graph",
     "gridPos": { "y": 28, "h": 8, "w": 9, "x": 15 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "topk(10, sum(netdata_openio_container_count__average) by (dimension))",
       "select": [
        [
         { "type": "field", "params": [ "value" ] },
         {
          "type": "mean",
          "params": []
         }
        ]
       ],
       "legendFormat": "{{dimension}}",
       "groupBy": [
        { "type": "time", "params": [ "$__interval" ] },
        { "type": "fill", "params": [ "null" ] }
       ]
      }
     ]
    },
    {
     "title": "Objects",
     "type": "singlestat",
     "gridPos": { "y": 33, "h": 5, "w": 6, "x": 0 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "expr": "sum(netdata_openio_container_objects__average{instance=~\"[[host]]\"})",
       "select": [
        [
         { "type": "field", "params": [ "value" ] },
         {
          "type": "mean",
          "params": []
         }
        ]
       ],
       "groupBy": [
        { "type": "time", "params": [ "$__interval" ] },
        { "type": "fill", "params": [ "null" ] }
       ]
      }
     ]
    },
    {
     "title": "Top 10 largest containers (object count)",
     "type": "graph",
     "gridPos": { "y": 36, "h": 8, "w": 9, "x": 6 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "topk(10, netdata_openio_container_objects__average)",
       "select": [
        [
         { "type": "field", "params": [ "value" ] },
         {
          "type": "mean",
          "params": []
         }
        ]
       ],
       "legendFormat": "{{dimension}}",
       "groupBy": [
        { "type": "time", "params": [ "$__interval" ] },
        { "type": "fill", "params": [ "null" ] }
       ]
      }
     ]
    },
    {
     "title": "Containers",
     "type": "singlestat",
     "gridPos": { "y": 38, "h": 6, "w": 6, "x": 0 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "expr": "sum(netdata_openio_container_count__average)",
       "select": [
        [
         { "type": "field", "params": [ "value" ] },
         {
          "type": "mean",
          "params": []
         }
        ]
       ],
       "groupBy": [
        { "type": "time", "params": [ "$__interval" ] },
        { "type": "fill", "params": [ "null" ] }
       ]
      }
     ]
    },
    { "type": "text", "gridPos": { "y": 44, "h": 2, "w": 24, "x": 0 }, "content": "# Bandwidth" },
    {
     "title": "Bandwidth",
     "type": "singlestat",
     "gridPos": { "y": 46, "h": 8, "w": 6, "x": 0 },
     "format": "KBs",
     "valueName": "avg",
     "targets": [
      {
       "expr": "sum(label_replace(netdata_web_log_bandwidth_kilobits_persec_average{dimension=\"received\", instance=~\"[[host]]\"}, \"chart2\", \"$1\", \"chart\", \".*openio[.](.*)[.].*.log.*\"))\n-sum(label_replace(netdata_web_log_bandwidth_kilobits_persec_average{dimension=\"sent\", instance=~\"[[host]]\"}, \"chart2\", \"$1\", \"chart\", \".*openio[.](.*)[.].*.log.*\"))",
       "select": [
        [
         { "type": "field", "params": [ "value" ] },
         {
          "type": "mean",
          "params": []
         }
        ]
       ],
       "groupBy": [
        { "type": "time", "params": [ "$__interval" ] },
        { "type": "fill", "params": [ "null" ] }
       ]
      }
     ]
    },
    {
     "title": "Bandwidth per service from logs",
     "type": "graph",
     "gridPos": { "y": 46, "h": 8, "w": 18, "x": 6 },
     "yaxes": [
      { "format": "KBs" }
     ],
     "targets": [
      {
       "expr": "sum(label_replace(netdata_web_log_bandwidth_kilobits_persec_average{dimension=\"received\", instance=~\"[[host]]\"}, \"chart2\", \"$1\", \"chart\", \".*openio[.](.*)[.].*.log.*\")) by (chart2)\n-sum(label_replace(netdata_web_log_bandwidth_kilobits_persec_average{dimension=\"sent\", instance=~\"[[host]]\"}, \"chart2\", \"$1\", \"chart\", \".*openio[.](.*)[.].*.log.*\")) by (chart2)",
       "alias": "$tag_namespace: $tag_servicetype",
       "tags": [
        { "operator": "=~", "value": "/^$host$/", "key": "host" },
        { "operator": "=", "value": "bytes_sent", "key": "type", "condition": "AND" }
       ],
       "select": [
        [
         { "type": "field", "params": [ "value" ] },
         {
          "type": "sum",
          "params": []
         }
        ]
       ],
       "legendFormat": "{{chart2}}",
       "measurement": "openio_log_bandwidth",
       "query": "SELECT (sum(\"value\") * -1) FROM \"[[DS]]\".\"openio_log_bandwidth\" WHERE \"namespace\" =~ /^$namespace$/ AND \"host\" =~ /^$host$/ AND \"type\" =~ /bytes_sent|sent/ AND $timeFilter GROUP BY time([[ds_int]]), \"servicetype\",\"namespace\" fill(null)",
       "groupBy": [
        { "type": "time", "params": [ "$__interval" ] },
        { "type": "tag", "params": [ "servicetype" ] },
        { "type": "fill", "params": [ "null" ] }
       ]
      }
     ]
    },
    { "type": "text", "gridPos": { "y": 54, "h": 2, "w": 24, "x": 0 }, "content": "# Requests" },
    {
     "title": "Response time",
     "type": "singlestat",
     "gridPos": { "y": 56, "h": 7, "w": 6, "x": 0 },
     "format": "ms",
     "valueName": "avg",
     "targets": [
      {
       "expr": "avg(netdata_netdata_response_time_ms_request_average{dimension=\"average\",instance=~\"[[host]]\"})",
       "select": [
        [
         { "type": "field", "params": [ "value" ] },
         {
          "type": "mean",
          "params": []
         }
        ]
       ],
       "groupBy": [
        { "type": "time", "params": [ "$__interval" ] },
        { "type": "fill", "params": [ "null" ] }
       ]
      }
     ]
    },
    {
     "title": "Response Time",
     "type": "graph",
     "gridPos": { "y": 56, "h": 7, "w": 9, "x": 6 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "sum(label_replace(netdata_web_log_response_time_milliseconds_average{family=\"timings\",instance=~\"[[host]]\"}, \"chart2\", \"$1\", \"chart\", \".*openio[.](.*)[.].*.log.*\")) by (chart2, dimension)",
       "alias": "$tag_namespace: $tag_servicetype: $tag_type",
       "tags": [
        { "operator": "=~", "value": "/^$host$/", "key": "host" }
       ],
       "select": [
        [
         { "type": "field", "params": [ "value" ] },
         {
          "type": "mean",
          "params": []
         }
        ]
       ],
       "legendFormat": "{{chart2}} {{dimension}}",
       "measurement": "openio_log_response_time",
       "query": "SELECT mean(\"value\") FROM \"[[DS]]\".\"openio_log_response_time\" WHERE \"namespace\" =~ /^$namespace$/ AND \"host\" =~ /^$host$/ AND $timeFilter GROUP BY time([[ds_int]]), \"servicetype\", \"namespace\", \"type\" fill(null)",
       "groupBy": [
        { "type": "time", "params": [ "$__interval" ] },
        { "type": "tag", "params": [ "servicetype" ] },
        { "type": "tag", "params": [ "type" ] },
        { "type": "fill", "params": [ "null" ] }
       ]
      }
     ]
    },
    {
     "title": "Errors",
     "type": "graph",
     "gridPos": { "y": 56, "h": 7, "w": 9, "x": 15 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(label_replace(netdata_web_log_response_codes_requests_persec_average{family=\"responses\", dimension=~\"4xx|5xx\", instance=~\"[[host]]\"}, \"chart2\", \"$1\", \"chart\", \".*openio[.](.*)[.].*.log.*\")) by (chart2, dimension)",
       "alias": "$tag_namespace: $tag_servicetype: $tag_type",
       "tags": [
        { "operator": "=~", "value": "/^$host$/", "key": "host" }
       ],
       "select": [
        [
         { "type": "field", "params": [ "value" ] },
         {
          "type": "sum",
          "params": []
         }
        ]
       ],
       "legendFormat": "{{chart2}} {{dimension}}",
       "measurement": "openio_log_response_codes",
       "query": "SELECT sum(\"value\")/($__interval_ms / 10000) FROM \"[[DS]]\".\"openio_log_response_codes\" WHERE \"namespace\" =~ /^$namespace$/ AND \"host\" =~ /^$host$/ AND (\"type\" = '5xx'  OR \"type\" = '4xx') AND $timeFilter GROUP BY time([[ds_int]]), \"servicetype\",\"namespace\", \"type\" fill(null)",
       "groupBy": [
        { "type": "time", "params": [ "$__interval" ] },
        { "type": "tag", "params": [ "servicetype" ] },
        { "type": "tag", "params": [ "type" ] },
        { "type": "fill", "params": [ "null" ] }
       ]
      }
     ]
    },
    {
     "title": "Responses Codes",
     "type": "graph",
     "gridPos": { "y": 63, "h": 7, "w": 9, "x": 6 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(label_replace(netdata_web_log_response_codes_requests_persec_average{family=\"responses\",instance=~\"[[host]]\"}, \"chart2\", \"$1\", \"chart\", \".*openio[.](.*)[.].*.log.*\")) by (dimension, chart2)",
       "alias": "$tag_namespace: $tag_servicetype: $tag_type",
       "tags": [
        { "operator": "=~", "value": "/^$host$/", "key": "host" }
       ],
       "select": [
        [
         { "type": "field", "params": [ "value" ] },
         {
          "type": "sum",
          "params": []
         }
        ]
       ],
       "legendFormat": "{{chart2}} {{dimension}}",
       "measurement": "openio_log_response_codes",
       "query": "SELECT sum(value) FROM \"[[DS]]\".\"openio_log_response_codes\" WHERE \"namespace\" =~ /^$namespace$/ AND \"host\" =~ /^$host$/ AND $timeFilter GROUP BY time([[ds_int]]), \"servicetype\",\"namespace\", \"type\" fill(null)",
       "groupBy": [
        { "type": "time", "params": [ "$__interval" ] },
        { "type": "tag", "params": [ "servicetype" ] },
        { "type": "tag", "params": [ "type" ] },
        { "type": "fill", "params": [ "null" ] }
       ]
      }
     ]
    },
    {
     "title": "Request Method",
     "type": "graph",
     "gridPos": { "y": 63, "h": 7, "w": 9, "x": 15 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(label_replace(netdata_web_log_http_method_requests_persec_average{instance=~\"[[host]]\"}, \"chart2\", \"$1\", \"chart\", \".*openio[.](.*)[.].*.log.*\")) by (chart2, dimension)",
       "alias": "$tag_namespace: $tag_servicetype: $tag_type",
       "tags": [
        { "operator": "=~", "value": "/^$host$/", "key": "host" }
       ],
       "select": [
        [
         { "type": "field", "params": [ "value" ] },
         {
          "type": "sum",
          "params": []
         }
        ]
       ],
       "legendFormat": "{{chart2}} {{dimension}}",
       "measurement": "openio_log_http_method",
       "query": "SELECT sum(\"value\") FROM \"[[DS]]\".\"openio_log_http_method\" WHERE \"namespace\" =~ /^$namespace$/ AND \"host\" =~ /^$host$/ AND $timeFilter GROUP BY time([[ds_int]]), \"servicetype\",\"namespace\", \"type\" fill(null)",
       "groupBy": [
        { "type": "time", "params": [ "$__interval" ] },
        { "type": "tag", "params": [ "servicetype" ] },
        { "type": "tag", "params": [ "type" ] },
        { "type": "fill", "params": [ "null" ] }
       ]
      }
     ]
    },
    { "type": "text", "gridPos": { "y": 70, "h": 2, "w": 24, "x": 0 }, "content": "# Redis" },
    {
     "title": "Keys",
     "type": "singlestat",
     "gridPos": { "y": 72, "h": 8, "w": 6, "x": 0 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "expr": "max(netdata_redis_keys_keys_average{instance=~\"[[host]]\"})"
      }
     ]
    },
    {
     "title": "Keys",
     "type": "graph",
     "gridPos": { "y": 72, "h": 8, "w": 9, "x": 6 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(label_replace(netdata_redis_keys_keys_average{instance=~\"[[host]]\"}, \"chart2\", \"$1\", \"chart\", \".*?_(.*).keys\")) by (chart2)",
       "select": [
        [
         { "type": "field", "params": [ "value" ] },
         {
          "type": "mean",
          "params": []
         }
        ]
       ],
       "legendFormat": "{{chart2}}",
       "groupBy": [
        { "type": "time", "params": [ "$__interval" ] },
        { "type": "fill", "params": [ "null" ] }
       ]
      }
     ]
    },
    {
     "title": "Operations",
     "type": "graph",
     "gridPos": { "y": 72, "h": 8, "w": 9, "x": 15 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(label_replace(netdata_redis_operations_operations_persec_average{instance=~\"[[host]]\"}, \"chart2\", \"$1\", \"chart\", \".*?_(.*).operations\")) by (chart2)\n",
       "select": [
        [
         { "type": "field", "params": [ "value" ] },
         {
          "type": "mean",
          "params": []
         }
        ]
       ],
       "legendFormat": "{{chart2}}",
       "groupBy": [
        { "type": "time", "params": [ "$__interval" ] },
        { "type": "fill", "params": [ "null" ] }
       ]
      }
     ]
    },
    {
     "title": "Hit rate",
     "type": "singlestat",
     "gridPos": { "y": 80, "h": 9, "w": 6, "x": 0 },
     "format": "percent",
     "valueName": "avg",
     "targets": [
      {
       "expr": "avg(netdata_redis_hit_rate_percent_average{instance=~\"[[host]]\"})",
       "select": [
        [
         { "type": "field", "params": [ "value" ] },
         {
          "type": "mean",
          "params": []
         }
        ]
       ],
       "groupBy": [
        { "type": "time", "params": [ "$__interval" ] },
        { "type": "fill", "params": [ "null" ] }
       ]
      }
     ]
    },
    {
     "title": "Memory",
     "type": "graph",
     "gridPos": { "y": 80, "h": 9, "w": 9, "x": 6 },
     "yaxes": [
      { "format": "deckbytes" }
     ],
     "targets": [
      {
       "expr": "sum(label_replace(netdata_redis_memory_kilobytes_average{dimension=\"total\",instance=~\"[[host]]\"}, \"chart2\", \"$1\", \"chart\", \"redis_(.*?).memory\")) by (chart2)",
       "legendFormat": "{{chart2}}"
      }
     ]
    },
    {
     "title": "Data Rate",
     "type": "graph",
     "gridPos": { "y": 80, "h": 9, "w": 9, "x": 15 },
     "yaxes": [
      { "format": "Kbits" }
     ],
     "targets": [
      {
       "expr": "sum(label_replace(netdata_redis_net_kilobits_persec_average{instance=~\"[[host]]\", dimension=\"in\"}, \"chart2\", \"$1\", \"chart\", \"redis_(.*?).net\")) by (chart2)\n- sum(label_replace(netdata_redis_net_kilobits_persec_average{instance=~\"[[host]]\", dimension=\"out\"}, \"chart2\", \"$1\", \"chart\", \"redis_(.*?).net\")) by (chart2)\n",
       "legendFormat": "{{chart2}}"
      }
     ]
    },
    { "type": "text", "gridPos": { "y": 89, "h": 2, "w": 24, "x": 0 }, "content": "# Events" },
    {
     "title": "Event queue",
     "type": "graph",
     "gridPos": { "y": 91, "h": 8, "w": 12, "x": 0 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(netdata_beanstalk_jobs_jobs_average{instance=~\"[[host]]\"}) by (family, dimension)",
       "alias": "$tag_namespace: $tag_tube: $tag_type",
       "tags": [
        { "operator": "=~", "value": "/^$host$/", "key": "host" },
        { "operator": "=~", "value": "/^current.*/", "key": "type", "condition": "AND" }
       ],
       "select": [
        [
         { "type": "field", "params": [ "value" ] },
         {
          "type": "sum",
          "params": []
         }
        ]
       ],
       "legendFormat": "{{ dimension }} {{ family }}",
       "measurement": "openio_beanstalkd_tubes",
       "query": "SELECT sum(\"value\") FROM \"[[DS]]\".\"openio_beanstalkd_tubes\" WHERE \"namespace\" =~ /^$namespace$/ AND \"host\" =~ /^$host$/ AND \"type\" =~ /^current.*/ AND $timeFilter GROUP BY time([[ds_int]]), \"namespace\", \"tube\", \"type\" fill(null)",
       "groupBy": [
        { "type": "time", "params": [ "$__interval" ] },
        { "type": "tag", "params": [ "namespace" ] },
        { "type": "tag", "params": [ "tube" ] },
        { "type": "tag", "params": [ "type" ] },
        { "type": "fill", "params": [ "null" ] }
       ]
      }
     ]
    },
    {
     "title": "Events Processing",
     "type": "graph",
     "gridPos": { "y": 91, "h": 8, "w": 12, "x": 12 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(netdata_beanstalk_jobs_rate_jobs_persec_average{chart=\"beanstalk_OPENIO_beanstalkd_1.jobs_rate\",family=\"server statistics\",dimension=\"total\",instance=~\"[[host]]\"})",
       "alias": "$tag_namespace: $tag_host: processed",
       "tags": [
        { "operator": "=~", "value": "/^$host$/", "key": "host" },
        { "operator": "=", "value": "total_jobs", "key": "type", "condition": "AND" }
       ],
       "select": [
        [
         { "type": "field", "params": [ "value" ] },
         {
          "type": "sum",
          "params": []
         },
         { "type": "non_negative_derivative", "params": [ "10s" ] }
        ]
       ],
       "legendFormat": "events",
       "measurement": "openio_beanstalkd_tubes",
       "query": "SELECT non_negative_derivative(sum(\"value\"), 10s) FROM \"[[DS]]\".\"openio_beanstalkd_tubes\" WHERE \"namespace\" =~ /^$namespace$/ AND \"host\" =~ /^$host$/ AND \"type\" = 'total_jobs' AND $timeFilter GROUP BY time([[ds_int]]), \"namespace\", \"type\", \"tube\", \"host\" fill(null)",
       "groupBy": [
        { "type": "time", "params": [ "$__interval" ] },
        { "type": "tag", "params": [ "namespace" ] },
        { "type": "tag", "params": [ "type" ] },
        { "type": "tag", "params": [ "tube" ] },
        { "type": "tag", "params": [ "host" ] },
        { "type": "fill", "params": [ "null" ] }
       ]
      }
     ]
    },
    { "type": "text", "gridPos": { "y": 99, "h": 2, "w": 24, "x": 0 }, "content": "# Zookeeper" },
    {
     "title": "Datasize",
     "type": "graph",
     "gridPos": { "y": 101, "h": 8, "w": 16, "x": 0 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "sum(netdata_openio_zk_approximate_data_size__average{chart=\"openio.zk_approximate_data_size\",family=\"Zookeeper\",instance=~\"[[host]]\"})",
       "alias": "$tag_namespace: approximate_data_size",
       "tags": [
        { "operator": "=~", "value": "/^$host$/", "key": "host" }
       ],
       "select": [
        [
         { "type": "field", "params": [ "value" ] },
         {
          "type": "mean",
          "params": []
         }
        ]
       ],
       "legendFormat": "data_size",
       "measurement": "openio_zookeeper_zk_approximate_data_size",
       "query": "SELECT mean(\"value\") FROM \"[[DS]]\".\"openio_zookeeper_zk_approximate_data_size\" WHERE \"namespace\" =~ /^$namespace$/ AND \"host\" =~ /^$host$/ AND $timeFilter GROUP BY time([[ds_int]]), \"namespace\" fill(null)",
       "groupBy": [
        { "type": "time", "params": [ "$__interval" ] },
        { "type": "tag", "params": [ "namespace" ] },
        { "type": "fill", "params": [ "null" ] }
       ]
      }
     ]
    },
    {
     "title": "Pending Syncs",
     "type": "graph",
     "gridPos": { "y": 101, "h": 8, "w": 8, "x": 16 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(netdata_openio_zk_pending_syncs__average{instance=~\"[[host]]\"}) by (dimension)",
       "alias": "$tag_namespace: pending_syncs",
       "tags": [
        { "operator": "=~", "value": "/^$host$/", "key": "host" }
       ],
       "select": [
        [
         { "type": "field", "params": [ "value" ] },
         {
          "type": "max",
          "params": []
         }
        ]
       ],
       "measurement": "openio_zookeeper_zk_pending_syncs",
       "query": "SELECT max(\"value\") FROM \"[[DS]]\".\"openio_zookeeper_zk_pending_syncs\" WHERE \"namespace\" =~ /^$namespace$/ AND \"host\" =~ /^$host$/ AND $timeFilter GROUP BY time([[ds_int]]), \"namespace\" fill(null)",
       "groupBy": [
        { "type": "time", "params": [ "$__interval" ] },
        { "type": "tag", "params": [ "namespace" ] },
        { "type": "fill", "params": [ "null" ] }
       ]
      }
     ]
    },
    {
     "title": "Latency",
     "type": "graph",
     "gridPos": { "y": 109, "h": 8, "w": 16, "x": 0 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "avg(netdata_openio_zk_max_latency__average{chart=\"openio.zk_max_latency\",family=\"Zookeeper\",instance=~\"[[host]]\"})\n",
       "alias": "$tag_namespace: avg_latency",
       "tags": [
        { "operator": "=~", "value": "/^$host$/", "key": "host" }
       ],
       "select": [
        [
         { "type": "field", "params": [ "value" ] },
         {
          "type": "mean",
          "params": []
         }
        ]
       ],
       "legendFormat": "max",
       "measurement": "openio_zookeeper_zk_avg_latency",
       "query": "SELECT mean(\"value\") FROM \"[[DS]]\".\"openio_zookeeper_zk_avg_latency\" WHERE \"namespace\" =~ /^$namespace$/ AND \"host\" =~ /^$host$/ AND $timeFilter GROUP BY time([[ds_int]]), \"namespace\" fill(null)",
       "groupBy": [
        { "type": "time", "params": [ "$__interval" ] },
        { "type": "tag", "params": [ "namespace" ] },
        { "type": "fill", "params": [ "null" ] }
       ]
      },
      {
       "expr": "avg(netdata_openio_zk_avg_latency__average{chart=\"openio.zk_avg_latency\",family=\"Zookeeper\",instance=~\"[[host]]\"})",
       "alias": "$tag_namespace: max_latency",
       "tags": [
        { "operator": "=~", "value": "/^$host$/", "key": "host" }
       ],
       "select": [
        [
         { "type": "field", "params": [ "value" ] },
         {
          "type": "mean",
          "params": []
         }
        ]
       ],
       "legendFormat": "average",
       "measurement": "openio_zookeeper_zk_max_latency",
       "query": "SELECT mean(\"value\") FROM \"[[DS]]\".\"openio_zookeeper_zk_avg_latency\" WHERE \"namespace\" =~ /^$namespace$/ AND \"host\" =~ /^$host$/ AND $timeFilter GROUP BY time([[ds_int]]), \"namespace\" fill(null)",
       "groupBy": [
        { "type": "time", "params": [ "$__interval" ] },
        { "type": "tag", "params": [ "namespace" ] },
        { "type": "fill", "params": [ "null" ] }
       ]
      }
     ]
    },
    {
     "title": "Outstanding Requests",
     "type": "graph",
     "gridPos": { "y": 109, "h": 8, "w": 8, "x": 16 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "avg(netdata_openio_zk_outstanding_requests__average{instance=~\"[[host]]\"})",
       "alias": "$tag_namespace: requests",
       "tags": [
        { "operator": "=~", "value": "/^$host$/", "key": "host" }
       ],
       "select": [
        [
         { "type": "field", "params": [ "value" ] },
         {
          "type": "max",
          "params": []
         }
        ]
       ],
       "legendFormat": "outstanding_requests",
       "measurement": "openio_zookeeper_zk_outstanding_requests",
       "query": "SELECT max(\"value\") FROM \"[[DS]]\".\"openio_zookeeper_zk_outstanding_requests\" WHERE \"namespace\" =~ /^$namespace$/ AND \"host\" =~ /^$host$/ AND $timeFilter GROUP BY time([[ds_int]]), \"namespace\" fill(null)",
       "groupBy": [
        { "type": "time", "params": [ "$__interval" ] },
        { "type": "tag", "params": [ "namespace" ] },
        { "type": "fill", "params": [ "null" ] }
       ]
      }
     ]
    }
   ]
  }
 ]
}